Added API handling to  messenger
drfifonz/news-feed-bot pull request #1
Opened 2022-02-27 22:09 UTC by drfifonz

2022-02-27 22:15 UTC, Vosloo requested changes

2022-02-27 22:15 UTC, Vosloo commented on src/bot_functions.py
> +    return response
Space between return and previous line

2022-02-27 22:15 UTC, Vosloo commented on src/bot_functions.py
> +def process_message(text):
Preferably add return types to methods: -> type

2022-02-27 22:15 UTC, Vosloo commented on src/messenger_bot.py
> +from bot_functions import process_message
Sort imports (use tool from VScode if you use it)

2022-02-27 22:15 UTC, Vosloo commented on src/messenger_bot.py
> +
Remove the newline

2022-02-27 22:15 UTC, Vosloo commented on src/messenger_bot.py
> +            return request.args.get("hub.challenge")
Do not hardcode values, move them to constants - applies to all hardcoded values - below as well

2022-02-27 22:15 UTC, Vosloo commented on src/messenger_bot.py
> +            # is returned even being sucesfully conected
Delete

2022-02-27 22:15 UTC, Vosloo commented on src/messenger_bot.py
> +        event = payload["entry"][0]["messaging"]
What is 0-th element of the entry? If it is unnecessary to split this line into multiple variables then explain what is happening with a comment.

2022-02-28 14:37 UTC, drfifonz commented on src/messenger_bot.py
> +            # is returned even being sucesfully conected
Flask needs to get some response

2022-04-05 19:24 UTC, closed without merging